### ISSUE TITLE
Run out of disk space

### ISSUE THREAD

**Issue by eddef** [mazaclub/EasyGitianBuilder#1]
When i start the building i end up with not enough diskspace.

`Insufficient space - 20GB required 6 available`

Even a EasyGitian rebuld_vm as it suggests, i still have the samme issue.

**Comment by guruvan** [comment]
This error will most typically occur if there was an uncaught error while installing the secondary virtual disk into the Virtualbox VM. 

The vagrant basebox used (debiancontrib-jessie) is too small.

To enlarge the single disk would require either 
A) producing our own basebox
OR
B) packaging the newly created vm and enlarging the root disk at that time

debiancontrib-jessie is an official debian basebox (contrib is for VBox Guest Additions) which is preferable to producing our own basebox in a non-public way. 

The simplest solution is to add the second disk for a build disk, which makes it easier to store old builds if needed. 

Closing this in favor of #2
