### ISSUE TITLE
keyserver fails to get keys

### ISSUE THREAD

**Issue by TerrenceHenry** [mazaclub/EasyGitianBuilder#14]
Error shows up as below:
+ gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys 51852D87348FFC4C
gpg: keyserver receive failed: No data
+ exit 9

To fix:
linux-Base-System.sh. line 24 should read
gpg --keyserver hkps://pgp.mit.edu  --recv-keys 51852D87348FFC4C || exit 9

It's possible that using hkp://pgp.mit.edu:80 may also work, but I haven't tested it.

Edit:
When retesting the above script it failed, as the mit server was not available.
Changing the server to point to the SKS pools worked, as shown below:
### **~/easygitianbuilder$ gpg --keyserver pool.sks-keyservers.net  --recv-keys 51852D87348FFC4C
gpg: key 51852D87348FFC4C: public key "HashiCorp Security <security@hashicorp.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1**

**Comment by guruvan** [comment]
thanks @TerrenceHenry  - I'll get this changed when I update the project over the next week or so  (pr is welcome of course) :)

**Comment by guruvan** [comment]
Fixed by #15
