### ISSUE TITLE
How to build from a custom repo?

### ISSUE THREAD

**Issue by akshaynexus** [mazaclub/EasyGitianBuilder#17]
as the title says,how can i build form a custom repo forked from PIVX?the script autocompiles/tries to autocompile from bitcoin-cash-abc.

**Comment by guruvan** [comment]
it sets up a variable in USER_CONFIG.env when USER_CONFIG.sh is run

You can rerun the configure by running 

EasyGitian make_env

You'll need the repo for gitian signatures and one for detached signatures to set easygitian up properly. 
 



On March 18, 2019 4:29:21 AM PDT, Akshay CM <notifications@github.com> wrote:
>as the title says,how can i build form a custom repo forked from
>PIVX?the script autocompiles/tries to autocompile from
>bitcoin-cash-abc.

-- 
Rob Nelson
guruvan@maza.club
530.859.3794

**Comment by akshaynexus** [comment]
Ok,did that,now this

1048576 bytes (1.0 MB) copied, 0.000813576 s, 1.3 GB/s
mke2fs 1.42.12 (29-Aug-2014)
Discarding device blocks: done
Creating filesystem with 3145728 4k blocks and 786432 inodes
Filesystem UUID: 2cf93d10-5595-424c-b6c4-4cdb70fe97f2
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208

Allocating group tables: done
Writing inode tables: done
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done

~
moving to build steps
Exiting gitian build

**Comment by akshaynexus** [comment]
nvm,i fixed that,now waiting on the compile

**Comment by guruvan** [comment]
Awesome....happy to help any time. 

On March 18, 2019 7:21:43 AM PDT, Akshay CM <notifications@github.com> wrote:
>nvm,i fixed that,now waiting on the compile

-- 
Rob Nelson
guruvan@maza.club
530.859.3794

**Comment by akshaynexus** [comment]
so i moved from my mac which as compiling fine,maybe deue to hardware limitations is stuck now

i see the script running in wsl,and its asking for this

vagrant@127.0.0.1's password:

is there any set passsword i can use?

**Comment by akshaynexus** [comment]
searching through google i found the default pass,now trying to rebuild the vm

**Comment by akshaynexus** [comment]
gitiian-builder and needed repositories will be downloaded and installed
/mnt/c/Users/Akshay/easygitianbuilder/Vagrantfile:81: warning: Insecure world writable dir /mnt/c in PATH, mode 040777
Bringing machine 'Gitian-builder_jessie' up with 'virtualbox' provider...
==> Gitian-builder_jessie: Importing base box 'debian/contrib-jessie64'...
==> Gitian-builder_jessie: Matching MAC address for NAT networking...
==> Gitian-builder_jessie: Checking if box 'debian/contrib-jessie64' is up to date...
==> Gitian-builder_jessie: Setting the name of the VM: Gitian-builder_jessie
The name of your virtual machine couldn't be set because VirtualBox
is reporting another VM with that name already exists. Most of the
time, this is because of an error with VirtualBox not cleaning up
properly. To fix this, verify that no VMs with that name do exist
(by opening the VirtualBox GUI). If they don't, then look at the
folder in the error message from VirtualBox below and remove it
if there isn't any information you need in there.

VirtualBox error:

VBoxManage.exe: error: Could not rename the directory 'C:\Users\Akshay\VirtualBox VMs\debiancontrib-jessie_1552923417973_53205' to 'C:\Users\Akshay\VirtualBox VMs\Gitian-builder_jessie' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3123 of file VBoxManageModifyVM.cpp

Trouble initializing VM - please report errors in an issue
at https://github.com/mazacub/easygitianbuilder
VM initialization failed

**Comment by guruvan** [comment]
You can login to the console of the virtualbox vm as vagrant with password vagrant. 

Vagrant should have set up an SSH key in the vm. You may need to rebuild the vm, or you may just setup a new SSH key manually by making a new key for the vagrant user and copying to the .vagrant directory in your easygitian work directory.

On March 18, 2019 8:32:24 AM PDT, Akshay CM <notifications@github.com> wrote:
>so i moved from my mac which as compiling fine,maybe deue to hardware
>limitations is stuck now
>
>i see the script running in wsl,and its asking for this
>
>vagrant@127.0.0.1's password:
>
>is there any set passsword i can use?

-- 
Rob Nelson
guruvan@maza.club
530.859.3794

**Comment by akshaynexus** [comment]
only have this issue now,mostly after that i dont think id have a issue compiling gitian releases

VirtualBox error:

VBoxManage.exe: error: Could not rename the directory 'C:\Users\Akshay\VirtualBox VMs\debiancontrib-jessie_1552923417973_53205' to 'C:\Users\Akshay\VirtualBox VMs\Gitian-builder_jessie' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3123 of file VBoxManageModifyVM.cpp

**Comment by akshaynexus** [comment]
fixed it by manually deleting leftover vm files

**Comment by guruvan** [comment]
You'll need to rebuild the vm I think. 

If you attempted to reuse a vm created in macOS on windows that wouldn't work. 

EasyGitian doesn't recover well (somewhat on purpose) from virtualbox configuration errors. 

Manually remove the vm in virtualbox and rebuild. 

On March 18, 2019 8:39:41 AM PDT, Akshay CM <notifications@github.com> wrote:
>only have this issue now,mostly after that i dont think id have a issue
>compiling gitian releases
>
>VirtualBox error:
>
>VBoxManage.exe: error: Could not rename the directory
>'C:\Users\Akshay\VirtualBox
>VMs\debiancontrib-jessie_1552923417973_53205' to
>'C:\Users\Akshay\VirtualBox VMs\Gitian-builder_jessie' to save the
>settings file (VERR_ALREADY_EXISTS)
>VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component
>SessionMachine, interface IMachine, callee IUnknown
>VBoxManage.exe: error: Context: "SaveSettings()" at line 3123 of file
>VBoxManageModifyVM.cpp

-- 
Rob Nelson
guruvan@maza.club
530.859.3794

**Comment by akshaynexus** [comment]
seems like its building atm,but i have one last question,i already have sdk for macos10.11 which is not in tar.gz format,can i use it with easygitianbuilder?

**Comment by guruvan** [comment]
You'll need one made as specified. Easygitian expects the tar.gz. 

On March 18, 2019 10:18:58 AM PDT, Akshay CM <notifications@github.com> wrote:
>seems like its building atm,but i have one last question,i already have
>sdk for macos10.11 which is not in tar.gz format,can i use it with
>easygitianbuilder?

-- 
Rob Nelson
guruvan@maza.club
530.859.3794

**Comment by akshaynexus** [comment]
one last thing,how do i compile from a commit has instead of release tags?

**Comment by guruvan** [comment]
When you run 

EasyGitian make_env 

It will ask for the version to build ( I.e. 0.14.6). Input a commit hash here _ the next question will verify it's a hash instead of a version release.


On March 19, 2019 2:33:18 AM PDT, Akshay CM <notifications@github.com> wrote:
>one last thing,how do i compile from a commit has instead of release
>tags?

-- 
Rob Nelson
guruvan@maza.club
530.859.3794

**Comment by akshaynexus** [comment]
ok thanks

**Comment by akshaynexus** [comment]
Compiling zenzo-core 2fca8681dcef738443638eab7a54c5300275a769 for Windows on Build ID: 62A28F5E at Fri Mar 22 12:21:28 GMT 2019

./bin/gbuild:282:in `block in <main>': must specify a commit for directory ZENZO-Core (RuntimeError)
        from ./bin/gbuild:279:in `each'
        from ./bin/gbuild:279:in `<main>'
./bin/gsign:52:in `<main>': invalid option: --detach-sign (OptionParser::InvalidOption)
cp: cannot stat ‘build/out/zenzo-core*-win-unsigned.tar.gz’: No such file or directory
cp: cannot stat ‘build/out/zenzo-core*.zip’: No such file or directory
cp: cannot stat ‘build/out/zenzo-core*.exe’: No such file or directory
cp: cannot stat ‘result/zenzo-core-win*.yml’: No such file or directory
########## DONE  Compiling zenzo-core 2fca8681dcef738443638eab7a54c5300275a769 for Windows on Build ID: 62A28F5E at Fri Mar 22 12:21:28 GMT 2019
~
~/gitian-builder ~

Signing 2fca8681dcef738443638eab7a54c5300275a769 Windows

sha256sum: zenzo-win-unsigned.tar.gz: No such file or directory
./bin/gbuild:282:in `block in <main>': must specify a commit for directory signature (RuntimeError)
        from ./bin/gbuild:279:in `each'
        from ./bin/gbuild:279:in `<main>'
./bin/gsign:52:in `<main>': invalid option: --detach-sign (OptionParser::InvalidOption)
mv: cannot stat ‘build/out/zenzo-core-*win64-setup.exe’: No such file or directory
mv: cannot stat ‘build/out/zenzo-core-*win32-setup.exe’: No such file or directory
~

**Comment by akshaynexus** [comment]
this is my config

export VGITIAN_BUILD=true
export VGITIAN_SETUPENV=false
export VGITIAN_LINUX=true
export VGITIAN_WIN=true
export VGITIAN_OSX=false
export VGITIAN_VERSION=2fca8681dcef738443638eab7a54c5300275a769
export VGITIAN_COMMIT=true
export VGITIAN_URL=https://github.com/zenzo-ecosystem/zenzo-core
export VGITIAN_COIN=zenzo-core
export VGITIAN_VERIFY=false
export VGITIAN_SIGREPO=https://github.com/pivx-project/gitian.sigs
export VGITIAN_DETACHEDSIGREPO=https://github.com/pivx-project/pivx-detached-sigs
export VGITIAN_ASSERT=true
export VGITIAN_SIGN=true
export VGITIAN_SIGNER=akshaycm@hotmail.com
export VGITIAN_COMMITFILES=false
export VGITIAN_PROC=8
export VGITIAN_MEM=14219
export EASYGITIAN_BUILD_ID=62A28F5E

**Comment by akshaynexus** [comment]
using the make
_env and it generated that,but still shows that error

**Comment by guruvan** [comment]
It's a little hard to say from the failure output. Any additional you could provide would be helpful.

The windows build appears to have failed to properly copy out the build artifacts for some reason. It's possible there is an Easygitian bug, or possible the windows build failed. 

I'm not currently able to run a build to reproduce your issue or I'd happily give it a go.  [I'm off grid, out of generator gas, out of funds, and looking for work]

On March 22, 2019 3:50:42 PM PDT, Akshay CM <notifications@github.com> wrote:
>using the make
>_env and it generated that,but still shows that error

-- 
Rob Nelson
guruvan@maza.club
530.859.3794
